language: python
python:
  - "3.5"
install: 
  - "pip install cython"
  - "pip install numpy"
  - "pip install . "
script: 
  - "python scripts/manage_api.py --testkey"
  - "python setup.py test"
branches:
  only:
  - master